# name: number-facts
# services:
#   numberFacts:
#     container_name: number-facts
#     build: .
#     restart: always
#     environment:
#       TZ: Africa/Lagos
#     logging:
#       driver: json-file
#     expose:
#       - 3000
#     volumes:
#       - ./:/usr/src/app
#     labels:
#       - 'traefik.enable=true'
#       - 'traefik.http.routers.number-facts.rule=Host(`stage1.dovely.tech`)'
#       - 'traefik.http.routers.number-facts.entrypoints=local'
#       - 'traefik.http.routers.number-facts.service=number-facts-service'
#       - 'traefik.http.services.number-facts-service.loadbalancer.server.port=3000'
#       - 'traefik.http.routers.number-facts.tls=true'
#       - 'traefik.http.routers.number-facts.tls.certresolver=myresolver'
#     networks:
#       - traefik

# networks:
#   traefik:
#     external: true
