name: stage-1
services:
  stage-1:
    container_name: stage-1
    image: ghcr.io/claudiusayadi/hng-12-stage-1:latest
    restart: always
    environment:
      TZ: Africa/Lagos
    logging:
      driver: json-file
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.stage-1.rule=Host(`stage1.claudiusa.xyz`)'
      - 'traefik.http.routers.stage-1.entrypoints=websecure'
      - 'traefik.http.routers.stage-1.service=stage-1-service'
      - 'traefik.http.services.stage-1-service.loadbalancer.server.port=3001'
      - 'traefik.http.routers.stage-1.tls=true'
      - 'traefik.http.routers.stage-1.tls.certresolver=myresolver'
    networks:
      - traefik

networks:
  traefik:
    external: true
