name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
        context: .
        file: ./stage_1/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        run: |
          docker login --username ${{ github.actor }} --password-stdin ${{ secrets.GHRC }} ghcr.io
          docker build . -t ghcr.io/hng-12-stage-1:latest
          docker push ghcr.io/hng-12-stage-1:latest
