name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHRC }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./stage_1
          file: ./stage_1/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/hng-12-stage-1:latest

      - name: Deploy Docker Stack on Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          script: |
            cd /home/deploy/apps/hng12
            echo "Copying docker-stack.yml..."
            scp -o StrictHostKeyChecking=no  ./stage_1/docker-stack.yml  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/deploy/apps/hng12/docker-stack.yml
            if [ $? -ne 0 ]; then
              echo "Failed to copy docker-stack.yml!"
              exit 1
            fi
            echo "Deploying docker stack..."
            docker stack deploy -c /home/deploy/apps/hng12/docker-stack.yml hng-12-stage-1
            if [ $? -ne 0 ]; then
              echo "Failed to deploy docker stack!"
              exit 1
            fi
            echo "Docker stack deployed successfully!"
