name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHRC }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./stage_1
          file: ./stage_1/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/hng-12-stage-1:latest

      - name: Deploy to Docker Swarm
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_KEY }}
          scp_source: ./stage_1/docker-stack.yml
          scp_target: ~/apps/hng12/stage-1-stack.yml
          args: |
            docker stack deploy -c ~/apps/hng12/stage-1-stack.yml hng-12-stage-1
